apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mydeploy
  name: mydeploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: my-test-webserver
  strategy: {}
  template:
    metadata:
      labels:
        app: my-test-webserver
    spec:
      containers:
      - image: k8s.gcr.io/test-webserver
        name: test-container
        resources: {}
        env:
         - name: SITE_HOST_NAME
           valueFrom:
             configMapKeyRef:
              name: my-app-config
              key: host_name
        envFrom:
        - secretRef:
           name: mysecret
        volumeMounts:
        - mountPath: /var/log
          name: log-vol
      volumes:
      - name: log-vol
        hostPath:
          path: /var/test-vol
          type: DirectoryOrCreate
status: {}
